# -*- coding: utf-8 -*-
"""Trees_DrSesh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDqyReFNXBiJANMBD_FTfAIiOSb8uG05
"""

import pandas as pd

x=pd.read_csv("trees.csv")

x.shape

x.head(10)

x['Girth'].mean()

x['Girth'].std()

x['Volume'].mean()

zoneA = x.loc[x['Zone']=='A']
zoneB = x.loc[x['Zone']=='B']

zoneB['Volume'].mean()

import matplotlib.pyplot as plt

plt.hist(x['Girth'])
plt.xlabel("Girth")

plt.plot(x['Girth'], x['Volume'], 'o', color = 'green')
plt.xlabel("Girth")
plt.ylabel("Volume")

plt.plot(x['Height'], x['Volume'], '1', color = 'red')
plt.xlabel("Height")
plt.ylabel("Volume")

import numpy as np

np.corrcoef(x['Girth'], x['Volume'])

np.corrcoef(x['Height'], x['Volume'])

pd.plotting.scatter_matrix(x, marker='o')